### ISSUE TITLE
“Interface conversion” error

### ISSUE THREAD

**Issue by gfscott** [tmaiaroto/go-lambda-geoip#1]
Thanks for this, it's a great idea.

I've set up a [test run](https://v4wc54uz93.execute-api.us-east-1.amazonaws.com/prod/geoip) and it’s currently throwing the following error:

`{"proc_req_id":4,"error":"panic: interface conversion: interface is nil, not string","data":null}`

From searching around this appears to be a Go issue and at that point my troubleshooting skills break down, I'm afraid. Any help appreciated!

**Comment by tmaiaroto** [comment]
Did you set up the mapping templates in AWS API Gateway? It needs to pass along the visitor's IP address. The interface should then not be nil. I think. I'll take a look as soon as I can and double check that something hasn't changed somewhere.

**Comment by gfscott** [comment]
That did it! It's always human error...
I think the step for editing the resource mapping might have changed slightly on Amazon’s end. (I saw no edit pencil, for instance.) Much obliged for the help!

Screenshot:
![](https://i.imgsafe.org/617dcf7.png)

**Comment by tmaiaroto** [comment]
Don't assume it's always human error =) 
You never know, there could have easily been a bug or Lambda could've changed or who knows. Glad it's working for you now.
